site_name: SmartSDK Recipes
site_description: Docker recipes for FIWARE Generic Enablers
docs_dir: 'recipes'
pages:
  - Home: index.md
  - 'Recipes':
    - 'Context Broker':
        - 'Simple': 'context-broker/simple/readme.md'
        - 'HA': 'context-broker/ha/readme.md'
        - 'Replica Set': 'context-broker/replica/readme.md'
    - 'Mongodb':
        - 'Replica Set': 'mongodb/replica/readme.md'
  - 'Tools': 'tools/readme.md'
theme: readthedocs
markdown_extensions: [toc,fenced_code]
extra_css: ["https://fiware.org/style/fiware_readthedocs.css"]
repo_url: https://github.com/martel-innovate/smartsdk-recipes
edit_uri: edit/master/recipes/
