mongo3:
  hostname: mongo3
  container_name: mongo3
  image: mongo:3.2
  entrypoint: [ "/usr/bin/mongod", "--replSet", "rs", "--journal", "--smallfiles", "--rest" ]
  volumes:
    - ./data3/:/data/db
  ports:
    - "27019:27017"
    - "28019:28017"
  restart: always

mongo2:
  hostname: mongo2
  container_name: mongo2
  image: mongo:3.2
  entrypoint: [ "/usr/bin/mongod", "--replSet", "rs", "--journal", "--smallfiles", "--rest" ]
  volumes:
    - ./data2/:/data/db
  ports:
    - "27018:27017"
    - "28018:28017"  # for http info
  restart: always

mongo1:
  hostname: mongo1
  container_name: mongo1
  image: mongo:3.2
  entrypoint: [ "/usr/bin/mongod", "--replSet", "rs", "--journal", "--smallfiles", "--rest" ]
  volumes:
    - ./data1/:/data/db
  ports:
    - "27017:27017"
    - "28017:28017"
  links:
    - mongo2:mongo2
    - mongo3:mongo3
  restart: always

# This configures the MongoDB replicaset
mongosetup:
  image: mongo:3.2
  links:
    - mongo1:mongo1
    - mongo2:mongo2
    - mongo3:mongo3
  volumes:
    - ./scripts/:/scripts
  entrypoint: [ "/scripts/setup_replica.sh" ]

orion:
    image: fiware/orion:latest
    hostname: orion
    container_name: orion
    links:
        - mongosetup
    expose:
        - "1026"
    ports:
        - "1026:1026"
    command: -dbhost mongo1
