orion:
    image: fiware/orion:latest
    hostname: orion
    container_name: orion
    links:
        - mongo1
    expose:
        - "1026"
    ports:
        - "1026:1026"
    volumes:
      - ./scripts/:/scripts
      - ../../../wait-for-it/:/wait-for-it
    entrypoint: /wait-for-it/wait-for-it.sh mongo1:27017 -t 30 -- sh /scripts/setup_orion.sh
