version: '3'
# NOTE: Default values of this recipe are aimed to work with
# ../../mongo/replica/docker-compose.yml.
services:

    orion:
        image: fiware/orion:1.3.0
        ports:
            - "1026:1026"
        # As host, we use the name of the orion service (mongo-replica_mongo)
        # And of course the same replicaset name
        command: -dbhost mongo-replica_mongo -rplSet rs -dbTimeout 10000
        deploy:
            replicas: 3
        networks:
            - mongo-replica_replica

networks:
    # Join the network of the db replicaset
    # defined in ../../mongodb/replica/docker-compose.yml
    mongo-replica_replica:
        external: true
