version: '3'

services:

    mongo:
      image: mongo
      entrypoint: [ "/usr/bin/mongod", "--replSet", "rs", "--journal", "--smallfiles"]
      ports:
        - "27017:27017"
      networks:
        - replica
      deploy:
        mode: global

    mongo-controller:
      # According to https://docs.docker.com/compose/compose-file/
      # "build" configuration is ignored in v3. Images must be pre-built.
      image: taliaga/mongo-replica-ctrl
      volumes:
        # TODO: Avoid exposing the docker socket (security issue)
        - /var/run/docker.sock:/var/run/docker.sock
      environment:
        # TODO: Dynamically populate these using common env variables with this compose file
        - OVERLAY_NETWORK_NAME=mongo-replica_replica
        - MONGO_SERVICE_NAME=mongo-replica_mongo
        - REPLICASET_NAME=rs
        - MONGO_PORT=27017
      entrypoint: python /src/replica_ctrl.py
      networks:
          - replica
      depends_on:
          - "mongo"
      deploy:
        placement:
          # Even with multiple managers, swarm deploys a single instance :)
          constraints: [node.role == manager]
        restart_policy:
          condition: none

networks:
    replica:
        driver: overlay
