version: '3'

services:

    mongo:
      image: mongo
      entrypoint: [ "/usr/bin/mongod", "--replSet", "rs", "--journal", "--smallfiles"]
      ports:
        - "27017:27017"
      networks:
        - replica
      deploy:
        mode: global

    mongo-controller:
      # According to https://docs.docker.com/compose/compose-file/
      # "build" configuration is ignored in v3. Images must be pre-built.
      # TODO: remember to push this image to a public registry
      image: mongo-replica-ctrl
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        # When ready remove this mount and embed the .py in the image
        - ./scripts/replica_ctrl.py:/src/replica_ctrl_tmp.py
      entrypoint: python /src/replica_ctrl_tmp.py
      networks:
          - replica
      depends_on:
          - "mongo"
      deploy:
        placement:
          constraints: [node.role == manager]  # TODO: Make sure it's only one.
        restart_policy:
          condition: none

networks:
    replica:
        driver: overlay
